# Change these first
owner: NTHU-SCOPELAB # Your GitHub organization or username, where this repository lives
repo: nthu-scopelab.github.io # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

assignees: # Users to assign downtime issues (optional)
  - pedestrianlove

status-website:
  theme: night
  baseUrl: / # where "repo" is your repository name
  name: SCOPELAB Server uptime
