# Change these first
owner: NTHU-SCOPELAB # Your GitHub organization or username, where this repository lives
repo: nthu-scopelab.github.io # The name of this repository

sites:
  - name: Google
    url: https://www.google.com

assignees: # Users to assign downtime issues (optional)
  - pedestrianlove

status-website:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/NTHU-SCOPELAB
  theme: night
  baseUrl: / # where "repo" is your repository name
  logoUrl: https://www.cs.nthu.edu.tw/~cherung/image001.png
  name: NTHU SCOPELAB Server uptime
