# Change these first
owner: NTHU-SCOPELAB # Your GitHub organization or username, where this repository lives
repo: nthu-scopelab.github.io # The name of this repository

sites:
  - name: GitLab Wiki
    url: https://makeitsimple.cs.nthu.edu.tw/

  - name: EE325 Jumphost(port 22)
    check: "tcp-ping"
    url: $EE325
    port: 22

  - name: EE325 Jumphost-dummy
    check: "tcp-ping"
    url: $EE325
    port: 2221
    
  - name: EE325 Jumphost(port 2222)
    check: "tcp-ping"
    url: $EE325
    port: 2222

assignees: # Users to assign downtime issues (optional)
  - pedestrianlove

status-website:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/NTHU-SCOPELAB
  theme: night
  baseUrl: / # where "repo" is your repository name
  logoUrl: https://www.cs.nthu.edu.tw/~cherung/image001.png
  name: NTHU SCOPELAB Server uptime
