# Change these first
owner: NTHU-SCOPELAB # Your GitHub organization or username, where this repository lives
repo: nthu-scopelab.github.io # The name of this repository

sites:
  - name: GitLab Wiki
    url: https://makeitsimple.cs.nthu.edu.tw/

  - name: EE325 Jumphost(port 22)
    check: "tcp-ping"
    url: $EE325
    port: 22
    
  - name: EE325 Jumphost(port 2222)
    check: "tcp-ping"
    url: $EE325
    port: 2222

  - name: R744 Jumphost(port 22)
    check: "tcp-ping"
    url: $R744
    port: 22

assignees: # Users to assign downtime issues (optional)
  - pedestrianlove

status-website:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/NTHU-SCOPELAB
  theme: dark
  logoUrl: https://www.cs.nthu.edu.tw/~cherung/image001.png
  name: Server Uptime
  cname: nthu-scopelab.github.io
